name: '0'
favicon: null
layout_spectrum: 0.9725393510889262
typography_spectrum: 0.14611464412882924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.009553444338962436
  lightness: 0.5844733724370599
  saturation: 0.07150621968321502
  rhythmicContrast: 0.7315450035966933
purpose: []
